services:
    iiwa_ws:
        build:
            context: .
            dockerfile: docker/iiwa/Dockerfile
        container_name: iiwa_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
            # - ROS_IP=172.31.1.150
            # - ROS_MASTER_URI=http://172.31.1.150:11311
            # - ROS_HOSTNAME=172.31.1.150
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./catkin_ws/src:/catkin_ws/src
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/noetic/setup.bash && cd /catkin_ws && catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 && bash"  
